I added a progress bar/value meter thing and a 16 bit register
Arctos6135/BeautifulRobot pull request #1
Opened 2019-01-22 20:13 UTC by squishybanana04

2019-01-22 20:13 UTC, squishybanana04 commented
I can't build it though cause I'm not set up

2019-01-23 03:00 UTC, tylertian123 requested changes
I mean, I like the idea of a progress bar mode, but eh, tbh there're a lot of things that you didn't need to do (and maybe shouldn't have done).

2019-01-23 03:00 UTC, tylertian123 commented on src/main.c
> +#define REG_SETVALUE_LSB 0x0A
I suggest following the naming convention and naming these `CMD_REG_MSB` or something similar.

2019-01-23 03:00 UTC, tylertian123 commented on src/main.c
> +#define CMD_RESET 0xff
`CMD_RESET` cannot be 0xFF, as the value 0xFF is already used for the sync byte which marks the termination of a command. Even though the command is only checked when the buffer is full, the value 0xFF as a command ID can have unintended consequences and mess with syncing.

2019-01-23 03:00 UTC, tylertian123 commented on src/main.c
> +{
I really don't get why you took the time to change every single pair of curly braces to a different style......

2019-01-23 03:00 UTC, tylertian123 commented on src/main.c
> +		reg = param | (reg >> 8) << 8;
Instead of doing `reg >> 8 << 8` just do `reg & 0xFF00`, it executes much faster and is more clear.

2019-01-23 03:00 UTC, tylertian123 commented on src/main.c
> +		((void(code *)(void))0x0000)();
What but why did you delete all the spaces....

2019-01-23 03:01 UTC, tylertian123 commented on src/main.c
> +		reg = param | (reg >> 8) << 8;
In the same way, change every `reg << 8 >> 8` to a `reg & 0x00FF`.

2019-01-23 03:22 UTC, squishybanana04 commented on src/main.c
> +#define REG_SETVALUE_LSB 0x0A
K thats a good idea. Idk why I wanted 16 bits lol.

2019-01-23 03:22 UTC, squishybanana04 commented on src/main.c
> +		reg = param | (reg >> 8) << 8;
Smort

2019-01-24 03:10 UTC, alexwaeseperlman commented
I just remembered why the FASTABS is faster than normal abs. It doesn't use any if statements which means it doesn't branch so its way easier for the processor.

2019-01-27 21:46 UTC, tylertian123 approved these changes

2019-01-27 21:46 UTC, merged